'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
<<<<<<< HEAD
'     the code is regenerated. 
=======
'     the code is regenerated.
>>>>>>> 28bc143fe84c59c07cbb4c3241c5faad893d2d77
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


<<<<<<< HEAD
=======

>>>>>>> 28bc143fe84c59c07cbb4c3241c5faad893d2d77
Partial Public Class Admin

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
<<<<<<< HEAD
    '''MainContent control.
=======
    '''ContentPlaceHolder1 control.
>>>>>>> 28bc143fe84c59c07cbb4c3241c5faad893d2d77
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
<<<<<<< HEAD
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
=======
    Protected WithEvents ContentPlaceHolder1 As Global.System.Web.UI.WebControls.ContentPlaceHolder
>>>>>>> 28bc143fe84c59c07cbb4c3241c5faad893d2d77
End Class
