'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Transaksi

    '''<summary>
    '''TbNamaPelanggan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TbNamaPelanggan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDLTipePelanggan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLTipePelanggan As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TbAlamatPelanggan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TbAlamatPelanggan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gvInventoryBuku control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvInventoryBuku As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''hfIdTransaksi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfIdTransaksi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''DDLJenisPembayaran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLJenisPembayaran As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TbPembayaran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TbPembayaran As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gvKeranjang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvKeranjang As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''TbTotalPembayaran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TbTotalPembayaran As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TbKembalian control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TbKembalian As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnBayar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBayar As Global.System.Web.UI.WebControls.Button
End Class
